name: Cypress Tests with Mochawesome

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Run Cypress tests
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config-file: cypress.config.js
          spec: cypress/e2e/FullPurchaseFlow.cy.js

      - name: Generate Mochawesome HTML report
        run: npm run posttest

      - name: Upload Mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html

      - name: Upload Cypress screenshots and videos (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-media
          path: |
            cypress/screenshots
            cypress/videos
